version: '2'
services:
  smokeping:
    image: linuxserver/smokeping
    container_name: smokeping
    volumes:
      - /home/rancher/smokeping/config:/config
      - /home/rancher/smokeping/data:/data
    ports:
      - 27025:80
    environment:
      - PUID=1100
      - PGID=1100
    restart: always