# Services to include:
# - keeweb
# - c9.io
# - dns
# - dhcp
# - nextcloud, projectsend or pydio
# - gitlab
# - ansible silo
# - lichee or photoshow


version: '2'
services:

  smokeping:
    image: linuxserver/smokeping
    container_name: smokeping
    volumes:
      - ${VOLUMES_ROOT}/smokeping/config:/config
      - ${VOLUMES_ROOT}/smokeping/data:/data
    ports:
      - "8001:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Paris
    restart: always

  portainer:
    image: portainer/portainer
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUMES_ROOT}/portainer:/data
    ports:
      - "8002:9000"
    restart: always

    #8003 is for awx to merge there

# docker-compose exec rest-server create_user backup
# TODO: add https://github.com/restic/rest-server/tree/master/examples/compose-with-grafana
  rest-server:
    image: restic/rest-server
    container_name: rest-server
    volumes:
      - ${VOLUMES_ROOT}/rest-server:/backups
    ports:
      - "8004:8000"
    environment:
      - OPTIONS="--prometheus"
    restart: always
