# Services to include:
# - smokeping
# - portainer
# - keeweb
# - borg backup server
# - c9.io
# - dns
# - dhcp
# - nextcloud
# - gitlab
# - ansible silo
# - lichee or photoshow


version: '2'
services:

  smokeping:
    image: linuxserver/smokeping
    container_name: smokeping
    volumes:
      - ${HOME}/mutualis-cloud/cloud/smokeping/config:/config
      - ${HOME}/mutualis-cloud/cloud/smokeping/data:/data
    ports:
      - 8001:80
    environment:
      - PUID=1100
      - PGID=1100
    restart: always
  
  portainer:
    image: portainer/portainer
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/mutualis-cloud/cloud/portainer/data:/data
    ports:
      - 8002:9000
    restart: always