# Services to include:
# - smokeping
# - portainer
# - keeweb
# - borg backup server
# - c9.io
# - dns
# - dhcp
# - nextcloud
# - gitlab
# - ansible silo
# - lichee or photoshow


version: '2'
services:

  smokeping:
    image: linuxserver/smokeping
    container_name: smokeping
    volumes:
      - ${VOLUMES_ROOT}/smokeping/config:/config
      - ${VOLUMES_ROOT}/smokeping/data:/data
    ports:
      - 8001:80
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Paris
    restart: always
  
  portainer:
    image: portainer/portainer
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUMES_ROOT}/portainer:/data
    ports:
      - 8002:9000
    restart: always