version: '3'
services:

  doods:
    image: snowzach/doods:latest
    container_name: doods
    ports:
      - "8080:8080"
    restart: unless-stopped

  portainer_edge_agent:
    image: portainer/agent
    container_name: portainer_agent
    command: -H unix:///var/run/docker.sock
    volumes:
      - /:/host
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUME_ROOT}/portainer_agent:/data
    environment:
      - EDGE=1
      - EDGE_ID=${EDGE_ID_CAM}
      - EDGE_KEY=${EDGE_KEY_CAM}
      - EDGE_INSECURE_POLL=1
    restart: unless-stopped