#! /bin/sh

SCRIPT_PATH=$(dirname $(realpath $0))
FILE="${SCRIPT_PATH}/${1}.yml"

case "$2" in
  start)
        docker-compose --file $FILE --env-file /mutualis-data/env up -d
        ;;
  stop)
        docker-compose --file $FILE --env-file /mutualis-data/env stop
        ;;

  restart)
        docker-compose --file $FILE --env-file /mutualis-data/env restart
        ;;

  status)
        docker-compose --file $FILE --env-file /mutualis-data/env ps -f
        ;;

  remove)
        docker-compose --file $FILE --env-file /mutualis-data/env stop
        docker-compose --file $FILE --env-file /mutualis-data/env rm -f
        ;;
  *)
        echo "Usage: dc {cloud|media|web|backup|gateway|...} {start|stop|restart|status|remove}"
        exit 1
esac

exit 0