#! /bin/sh

SCRIPT_PATH=$(dirname $(realpath $0))
FILE="${1}.yml"

case "$2" in
  start)
        docker-compose up -d -f $FILE --env-file /mutualis-data/env
        ;;
  stop)
        docker-compose stop -f $FILE --env-file /mutualis-data/env
        ;;

  restart)
        docker-compose restart -f $FILE --env-file /mutualis-data/env
        ;;

  status)
        docker-compose ps -f $FILE --env-file /mutualis-data/env
        ;;

  remove)
        docker-compose stop -f $FILE --env-file /mutualis-data/env
        docker-compose rm -f $FILE --env-file /mutualis-data/env
        ;;
  *)
        echo "Usage: dc {cloud|media|wordpress} {start|stop|restart|status|remove}"
        exit 1
esac

exit 0