version: '2.0'
services:
  db:
    image: mariadb:10.5
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${SEAFILE_DB_PASSWORD} # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /opt/seafile-mysql/db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net

  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net
          
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    ports:
      - "80:80"
#     - "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - ${VOLUME_ROOT}/seafile:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=${SEAFILE_DB_PASSWORD}  # Requested, the value shuold be root's password of MySQL service.
      - TIME_ZONE=${TZ} # Optional, default is UTC. Should be uncomment and set to your local time zone.
#      - SEAFILE_ADMIN_EMAIL=me@example.com # Specifies Seafile admin user, default is 'me@example.com'.
#      - SEAFILE_ADMIN_PASSWORD=asecret     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME=${SEAFILE_HOST} # Specifies your host name if https is enabled.
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net

  portainer_edge_agent:
    image: portainer/agent
    container_name: portainer_agent
    command: -H unix:///var/run/docker.sock
    volumes:
      - /:/host
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUME_ROOT}/portainer_agent:/data
    environment:
      - EDGE=1
      - EDGE_ID=${EDGE_ID_DRIVE}
      - EDGE_KEY=${EDGE_KEY_DRIVE}
      - EDGE_INSECURE_POLL=1
    restart: unless-stopped

networks:
  seafile-net:



