
version: '3'
services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      - DB_SQLITE_FILE=/data/database.sqlite
    volumes:
      - ${VOLUME_ROOT}/npm/data:/data
      - ${VOLUME_ROOT}/npm/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  portainer_edge_agent:
    image: portainer/agent
    command: -H unix:///var/run/docker.sock
    volumes:
      - /:/host
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUME_ROOT}/portainer_agent:/data
    environment:
      - CAP_HOST_MANAGEMENT=1
      - EDGE=1
      - EDGE_ID=[YOUR EDGE ID]
      - EDGE_KEY=[YOUR EDGE KEY]
    restart: unless-stopped
