# dragas/nikola ?

# version: '2'
# services:
#   nginx:
#     image: evild/alpine-nginx:1.11.2-libressl
#     container_name: wordpress_nginx
#     restart: always
#     volumes:
#       - wordpress-data:/var/www/html/:ro
#       - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
#       - ./nginx/conf.d:/etc/nginx/conf.d:ro
#     ports:
#       - 8081:80
#       - 443:443
#     networks:
#       - front
#   php:
#     image: evild/alpine-wordpress:4.5.3
#     container_name: wordpress_php
#     restart: always
#     volumes:
#       - wordpress-data:/var/www/html
#       - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
#     environment:
#       - WORDPRESS_DB_NAME=wpdb
#       - WORDPRESS_TABLE_PREFIX=wp_
#       - WORDPRESS_DB_HOST=db
#       - WORDPRESS_DB_PASSWORD=aqwzsxedc
#     networks:
#       - back
# volumes:
#   wordpress-data:
#     driver: local
#   wordpress-db-data:
#     driver: local
# networks:
#   front:
#   back:

version: '3'

services:
  nginx:
    image: yobasystems/alpine-grav
    container_name: grav
    restart: always
    volumes:
      - ./grav:/usr/html
    ports:
      - 8000:80

  portainer_agent:
    image: portainer/agent
    container_name: agent
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: always