# add ha-proxy docker version


version: '3'
services:

  portainer:
    image: portainer/portainer
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUMES_ROOT}/portainer:/data
    ports:
      - "9000:9000"
    restart: always
