version: '3.0'

services:
  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - ./minio:/data
    ports:
      - "8000:9000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always






# Services to include:

# version: '3'
# services:

#   portainer:
#     image: portainer/portainer
#     container_name: portainer
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - ./portainer:/data
#     ports:
#       - "9000:9000"
#     restart: always

# # docker-compose exec rest-server create_user backup
#   rest-server:
#     image: restic/rest-server
#     container_name: rest-server
#     volumes:
#       - ./rest-server:/data
#     ports:
#       - "8000:8000"
#     environment:
#       - "OPTIONS=--prometheus"
#     restart: always

#   prometheus:
#     image: prom/prometheus
#     container_name: prometheus
#     ports:
#       - "8001:9090"
#     volumes:
#       - ./prometheus/data:/prometheus
#       - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
#     environment:
#       - PUID=${PUID}
#       - PGID=${PGID}
#     depends_on:
#       - rest-server

#   grafana:
#     image: grafana/grafana
#     container_name: grafana
#     volumes:
#       - ./grafana/data:/var/lib/grafana
#       - ./grafana/dashboards:/dashboards
#       - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
#     ports:
#       - "8002:3000"
#     environment:
#       GF_USERS_DEFAULT_THEME: light
#     #  GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
#     depends_on:
#       - prometheus
