# Services to include:
# - borg backup client
# - dns
# - dhcp
# - omv
# - plex or equivalent
# - lms
# - hass.io

version: '2'
services:

  portainer:
    container_name: portainer
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUMES_ROOT}/portainer:/data
    ports:
      - 9000:9000
    restart: always

  muximux:
    container_name: muximux
    image: linuxserver/muximux
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${VOLUMES_ROOT}/muximux:/config
    ports:
      - 80:80
    restart: always

  keeweb:
    container_name: keeweb
    image: antelle/keeweb
    volumes:
      - ${VOLUMES_ROOT}/keeweb:/etc/nginx/external/
    ports:
      - 8002:443
    restart: always

  pyload:
    container_name: pyload
    image: writl/pyload:0.4.9
    volumes:
      - /tmp:/opt/pyload/Downloads
      - ${VOLUMES_ROOT}/pyload:/opt/pyload/pyload-config
    ports:
      - 8003:8000
    restart: always

  smb:
    container_name: smb
    image: jenserat/samba-publicshare:latest
    volumes:
      - /tmp:/srv
    ports:
      - 137:137
      - 138:139
      - 139:139
      - 445:445
    restart: always

  openvpn:
    container_name: openvpn
    image: kylemanna/openvpn:latest
    volumes:
      - ${VOLUMES_ROOT}/openvpn:/etc/openvpn
    ports:
      - 1194/udp:1194
    restart: always

  ansible:
    container_name: ansible
    image: grpn/ansible-silo:latest
    volumes:
      - /usr/local/bin:/silo_install_path
    restart: always

  duckdns:
    container_name: duckdns
    image: linuxserver/duckdns:latest
    environment:
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
      - PUID=${PUID}
      - PGID=${PGID}
    restart: always

  cups:
    container_name: cups
    image: mnbf9rca/cups-google-print
    environment:
      - CUPS_USER_ADMIN=${CUPS_USER_ADMIN}
      - CUPS_USER_PASSWORD=${CUPS_USER_PASSWORD}
      - TZ=Europe/Paris
      - TCP_PORT_631=631
    volumes:
      - ${VOLUMES_ROOT}/cups:/config
      - /dev:/dev
      - /etc/avahi/services:/avahi
      - /var/run/dbus:/var/run/dbus
    network_mode: "host"
    privileged: true
    restart: always

  glances:
    image: docker.io/nicolargo/glances
    container_name: glances
    ports:
      - "9001-9002:61208-61209"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GLANCES_OPT=-w
    pid: "host"

  watchtower:
    container_name: watchtower
    image: v2tec/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
