# Services to include:
# - omv
# - plex or equivalent
# - lms
# - hass.io

version: '2'
services:

  portainer:
    container_name: portainer
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUMES_ROOT}/portainer:/data
    ports:
      - 9000:9000
    restart: always

  organizr:
    container_name: organizr
    image: lsiocommunity/organizr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${VOLUMES_ROOT}/organizr:/config
    ports:
      - 80:80
    restart: always

  keeweb:
    container_name: keeweb
    image: antelle/keeweb
    volumes:
      - ${VOLUMES_ROOT}/keeweb:/etc/nginx/external/
    ports:
      - 8002:443
    restart: always

  pyload:
    container_name: pyload
    image: writl/pyload:0.4.9
    volumes:
      - /tmp:/opt/pyload/Downloads
      - ${VOLUMES_ROOT}/pyload:/opt/pyload/pyload-config
    ports:
      - 8003:8000
    restart: always

  smb:
    container_name: smb
    image: jenserat/samba-publicshare:latest
    volumes:
      - /tmp:/srv
    ports:
      - 137:137
      - 138:139
      - 139:139
      - 445:445
    environment:
      - workgroup=WORKGROUP
    tty: true
    restart: always

  openvpn:
    container_name: openvpn
    image: kylemanna/openvpn:latest
    volumes:
      - ${VOLUMES_ROOT}/openvpn:/etc/openvpn
    ports:
      - 1194:1194/udp
    cap_add:
      - NET_ADMIN
    privileged: true
    restart: always

  duckdns:
    container_name: duckdns
    image: linuxserver/duckdns:latest
    environment:
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
      - PUID=${PUID}
      - PGID=${PGID}
    restart: always

  dnsmasq:
    container_name: dnsmasq
    image: andyshinn/dnsmasq:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    volumes:
      - ${VOLUMES_ROOT}/dnsmasq:/tmp
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    command: "--domain=${DOCKER_DNS_DOMAIN} --dhcp-range=${DOCKER_DHCP_RANGE},24h --addn-hosts=/tmp/dns-hosts --dhcp-hostsfile=/tmp/dhcp-hosts --dhcp-optsfile=/tmp/dhcp-options --log-facility=-"
    restart: always

  cups:
    container_name: cups
    image: mnbf9rca/cups-google-print
    environment:
      - CUPS_USER_ADMIN=${CUPS_USER_ADMIN}
      - CUPS_USER_PASSWORD=${CUPS_USER_PASSWORD}
      - TZ=Europe/Paris
      - TCP_PORT_631=631
    volumes:
      - ${VOLUMES_ROOT}/cups:/config
      - /dev:/dev
      - /etc/avahi/services:/avahi
      - /var/run/dbus:/var/run/dbus
    network_mode: "host"
    privileged: true
    restart: always

  glances:
    image: docker.io/nicolargo/glances
    container_name: glances
    ports:
      - "9001-9002:61208-61209"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GLANCES_OPT=-w
    pid: "host"
    restart: always

  borgmatic:
    image: b3vis/borgmatic
    container_name: borg
    volumes:
      - ${VOLUMES_ROOT}/borg/backups:/source/home:ro
      - /home/core/.ssh:/root/.ssh:ro
      - ${VOLUMES_ROOT}/borg/config:/config
      - ${VOLUMES_ROOT}/borg/cache:/cache
    environment:
      - BORG_PASSPHRASE=${BORG_PASSPHRASE}
    restart: always

# docker-compose exec zerotier /zerotier-cli join ${ZEROTIER_NETWORK}
  zerotier:
    image: zerotier/zerotier-containerized
    container_name: zerotier
    volumes:
      - ${VOLUMES_ROOT}/zerotier:/var/lib/zerotier-one
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    network_mode: "host"
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: always

  gogs:
    image: gogs/gogs
    container_name: gogs
    volumes:
      - ${VOLUMES_ROOT}/gogs:/data
    ports:
      - "9005:22"
      - "8005:3000"
    restart: always

  fava:
    image: yegle/fava
    container_name: fava
    volumes:
      - ${VOLUMES_ROOT}/fava:/root
    environment:
      - BEANCOUNT_INPUT_FILE=/root/main.beancount
    ports:
      - "8004:5000"
    restart: always

# To uncomment if you want to manage upgrade of docker images automatically
# Until docker-compose issue #1896 becomes available
#  watchtower:
#    container_name: watchtower
#    image: v2tec/watchtower:latest
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    restart: always

# SMARTPHONES
b0:19:c6:b4:82:2f,iphone_x,192.168.1.150,infinite
c0:ee:fb:58:e2:20,oneplus_onex,192.168.1.151,infinite
54:e4:3a:28:fe:75,iphone_5S,192.168.1.152,infinite
38:f2:3e:23:af:30,lumia,192.168.1.153,infinite

# TABLETS
54:e4:3a:dd:b6:56,ipad_mini,192.168.1.160,infinite
dc:a4:ca:dc:c9:35,ipad_pro,192.168.1.161,infinite
ff:ff:ff:ff:ff:ff,ipad_un,192.168.1.162,infinite
ff:ff:ff:ff:ff:ff,archos,192.168.1.163,infinite

# EREADERS
84:d6:d0:45:1f:cd,kindle_evy,192.168.1.170,infinite
ff:ff:ff:ff:ff:ff,kindle_mia,192.168.1.171,infinite
ff:ff:ff:ff:ff:ff,kindle_momo,192.168.1.172,infinite
ff:ff:ff:ff:ff:ff,nook_juju,192.168.1.173,infinite
