# Services to include:
# - portainer
# - keeweb
# - borg backup client
# - dns
# - dhcp
# - ansible silo
# - omv
# - pyload
# - openvpn
# - plex or equivalent
# - lms
# - hass.io

version: '2'
services:

  portainer:
    image: portainer/portainer
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/mutualis-cloud/cloud/portainer/data:/data
    ports:
      - 8000:9000
    restart: always

  keeweb:
    container_name: keeweb
    image: antelle/keeweb
    volumes:
      - ${HOME}/mutualis-cloud/cloud/keeweb:/etc/nginx/external/
    ports:
      - 8001:80
      - 8002:443
    restart: always

  duckdns:
    container_name: duckdns
    image: linuxserver/duckdns:latest
    environment:
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
      - PUID=${PUID}
      - PGID=${PGID}
    restart: always
