version: "2"
services:
  pyload:
    image: writl/pyload:latest
    container_name: pyload
    ports:
      - 8001:8000
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - ${DOWNLOAD}:/opt/pyload/Downloads
      - ./pyload:/opt/pyload/pyload-config
    restart: always