# dragas/nikola ?

# version: '2'
# services:
#   nginx:
#     image: evild/alpine-nginx:1.11.2-libressl
#     container_name: wordpress_nginx
#     restart: always
#     volumes:
#       - wordpress-data:/var/www/html/:ro
#       - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
#       - ./nginx/conf.d:/etc/nginx/conf.d:ro
#     ports:
#       - 8081:80
#       - 443:443
#     networks:
#       - front
#   php:
#     image: evild/alpine-wordpress:4.5.3
#     container_name: wordpress_php
#     restart: always
#     volumes:
#       - wordpress-data:/var/www/html
#       - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
#     environment:
#       - WORDPRESS_DB_NAME=wpdb
#       - WORDPRESS_TABLE_PREFIX=wp_
#       - WORDPRESS_DB_HOST=db
#       - WORDPRESS_DB_PASSWORD=aqwzsxedc
#     networks:
#       - back
# volumes:
#   wordpress-data:
#     driver: local
#   wordpress-db-data:
#     driver: local
# networks:
#   front:
#   back:

version: '3'

services:
  nginx:
    image: yobasystems/alpine-grav
    container_name: grav
    restart: always
    volumes:
      - ${VOLUMES_ROOT}/grav:/usr/html
    ports:
      - 8000:80

  strapi:
    image: strapi/strapi
    container_name: strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - HOST=localhost
    ports:
      - 8001:1337
    volumes:
      - ${VOLUMES_ROOT}/strapi/app:/usr/src/api/strapi-app
      - ${VOLUMES_ROOT}/strapi/node_modules/usr/src/api/node_modules
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - ${VOLUMES_ROOT}/strapi/db:/data/db
    restart: always
